language: python
matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    - python: "2.7.10"
    - python: "2.7.11"
  allow_failures:
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "nightly"

install:
    - pip install pytest
script: py.test -v